# numpy基础练习（满分100，每题5分）

1. 导入numpy库并取别名为np

In [1]:
import numpy as np

2. 创建一个长度为10的空向量，并输出结果

In [2]:
vec1 = np.zeros(10)
print(vec1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. 创建一个长度为10的向量（要求除了第五个值为1之外，其他值均为0），并输出结果

In [3]:
vec2 = np.zeros(10)
vec2[4] = 1
print(vec2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. 创建一个值域范围从10到49的向量，并输出结果

In [4]:
vec3 = np.arange(10,50)
print(vec3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5. 创建一个3x3并且值从0到8的矩阵，并输出结果

In [5]:
arr1 = np.arange(9).reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. 对于上一题中创建的矩阵，输出其中的第二行第三列的元素

In [6]:
x = arr1[1,2]
print(x)

5


7. 创建一个3x3的单位矩阵，并输出结果

In [7]:
arr2 = np.eye(3)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. 创建一个10x10的随机矩阵，找到他的最大值和最小值，输出矩阵以及最大值和最小值

In [8]:
arr3 = np.random.random((10,10))
print(arr3)
print(arr3.max())
print(arr3.min())

[[0.00365077 0.49660126 0.3349862  0.57539766 0.94863261 0.53445436
  0.97502759 0.13456048 0.21885833 0.70220993]
 [0.02351096 0.8907895  0.82779557 0.7241407  0.57587319 0.09039001
  0.75231256 0.97775247 0.22332341 0.47304739]
 [0.19446107 0.75434586 0.6803956  0.46506081 0.56058438 0.07966519
  0.8836333  0.44072669 0.37633149 0.34103564]
 [0.32808921 0.48574472 0.86207332 0.11520527 0.11864577 0.70290524
  0.36095483 0.07811936 0.06420281 0.82087677]
 [0.60746706 0.92337056 0.31890224 0.78617406 0.85569566 0.52484662
  0.33517912 0.98151412 0.48477695 0.64161406]
 [0.58354447 0.1379417  0.46648555 0.76459025 0.94942921 0.63174742
  0.88161718 0.78423459 0.07692057 0.16921623]
 [0.36260801 0.06736173 0.36339232 0.87806531 0.84362812 0.79325944
  0.15667086 0.41522289 0.5683167  0.1587074 ]
 [0.43841719 0.91696522 0.64747957 0.0096396  0.7932527  0.038414
  0.33480343 0.93517541 0.09645859 0.69202045]
 [0.0701418  0.95076773 0.46461683 0.51593545 0.44947356 0.56883751
  0.13957623 0

9. 对一个5x5的随机矩阵做归一化（提示：(x-min)/(max-min)），并输出归一化之后的结果

In [9]:
arr4 = np.random.random((5,5))
arr4 = (arr4-arr4.min())/(arr4.max()-arr4.min())
print(arr4)

[[0.37228325 0.1853741  0.29632354 0.68025812 0.98081974]
 [0.72507635 0.70472486 0.3960609  0.64521708 0.96453248]
 [0.86586595 0.46750138 0.1683189  0.83783031 0.50509828]
 [0.1278999  0.67210476 0.31272969 0.29577055 0.        ]
 [0.75664745 0.3610095  0.21718964 0.20014243 1.        ]]


10. 对矩阵A求转置并输出

In [10]:
A = np.array([[1,2,3],[4,5,6]],dtype=np.float64)
print(A.T)

[[1. 4.]
 [2. 5.]
 [3. 6.]]


11. 对本题中给出的两个矩阵进行加法操作并输出结果

In [11]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)

[[ 6.  8.]
 [10. 12.]]


12. 对本题中给出的两个矩阵进行减法操作（以x为被减数，y为减数）并输出结果

In [12]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
print(x-y)

[[-4. -4.]
 [-4. -4.]]


13. 对本题中给出的两个矩阵，进行对应位置相乘的操作并输出结果

In [13]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
print(x*y)

[[ 5. 12.]
 [21. 32.]]


14. 对本题中给出的两个矩阵，进行矩阵乘法的操作并输出结果

In [14]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
print(np.dot(x,y))


[[19. 22.]
 [43. 50.]]


15. 对数组B中的每一项进行向下取整，并输出向下取整后的数组

In [15]:
B = np.random.uniform(0,10,10)
print(B)
print(np.floor(B))


[4.755713   9.90444101 8.32146876 5.04497513 2.93156557 3.49362727
 6.74637118 1.75464663 4.37094006 7.29180468]
[4. 9. 8. 5. 2. 3. 6. 1. 4. 7.]


16. 创建一个长度为11的向量，要求这11个数字是0到1之间的等差数列，第一个元素为0，最后一个元素为1，并输出该向量

In [16]:
vec4 = np.linspace(0,1,11)
print(vec4)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


17. 输出对16题中创建的向量进行求和（即各项相加，最终得到一个数字）得到的结果（可能会有很小的计算错误，可以忽视或者只保留一位小数）

In [17]:
vec4.sum()

5.500000000000001

18. 输出16题中创建的向量的均值（直接调用numpy中的函数实现这一点，不要自己写公式）

In [18]:
vec4.mean()

0.5000000000000001

19. 对16题创建的向量中的所有元素求平方，并输出结果

In [19]:
print(vec4**2)

[0.   0.01 0.04 0.09 0.16 0.25 0.36 0.49 0.64 0.81 1.  ]


20. 对16题创建的向量中的所有元素开平方，并输出结果

In [20]:
print(np.sqrt(vec4))

[0.         0.31622777 0.4472136  0.54772256 0.63245553 0.70710678
 0.77459667 0.83666003 0.89442719 0.9486833  1.        ]
